profile = "dev"

[server]
addr = "127.0.0.1"
port = 8_080

[db]
host = "127.0.0.1"
port = 5_432
username = "lkw"
password = "root"
database_name = "axum"
max_connections = 5
logging = false

[redis]
username = "default"
password = ""
host = "127.0.0.1"
port = 6_379
database_name = ""

[email]
username = "450733477@qq.com"
password = "xaqttfjqiqvibjjb"
host = "smtp.qq.com"
port = 465

[sentry]
key = "https://92654da696494bd2b88f06438aef9fb3@o1055779.ingest.sentry.io/6583480"

[secret]
private_access_key = "static/key/private_access_rsa_key.pem"
public_access_key = "static/key/public_access_rsa_key.pem"
private_refresh_key = "static/key/private_refresh_rsa_key.pem"
public_refresh_key = "static/key/public_refresh_rsa_key.pem"

[worker]
failed_task_delay = 50

[http]
timeout = 10

